### ISSUE TITLE
Duplicate TOC for OCP 3.11 OpenAPI

### ISSUE THREAD

**Issue by jboxman** [jboxman/openshift-apidocs-gen#2]
So what causes a duplicate `Template` to appear?

```
- Name: template.openshift.io
  Dir: template_openshift_io
  Topics:
  - Name: About template.openshift.io
    File: template-openshift-io-index
  - Name: 'BrokerTemplateInstance [template.openshift.io/v1]'
    File: brokertemplateinstance-template-openshift-io-v1
  - Name: 'Template [template.openshift.io/v1]'
    File: template-template-openshift-io-v1
  - Name: 'TemplateInstance [template.openshift.io/v1]'
    File: templateinstance-template-openshift-io-v1
  - Name: 'Template [template.openshift.io/v1]'
    File: template-template-openshift-io-v1
```
