### ISSUE TITLE
Feat: Include examples in output

### ISSUE THREAD

**Issue by jboxman** [jboxman/openshift-apidocs-gen#30]
It's possible to inject example YAML object definitions from the configuration file:

```yaml
example1: |
  foo: bar
  array: []
```

Is this part of the `apiMap`, or does it live elsewhere? The `apiMap` includes both what APIs to include and where. Overloading with other information, such as examples, is not ideal.
