### ISSUE TITLE
Feat: Ignore a resource in a map

### ISSUE THREAD

**Issue by jboxman** [jboxman/openshift-apidocs-gen#5]
Instead of commenting out a resource, disable it. This way, the API is not erroneously detected as a _new_ API when a `changelog` is run. Default to false if not specified.

If all entries are disabled for a group, the group must not explode.

```yaml
  - kind: Binding
    group: core
    version: v1
    plural: bindings
    namespaced: true
    hide: true # Or similar
```
