### ISSUE TITLE
Feat: API support levels

### ISSUE THREAD

**Issue by jboxman** [jboxman/openshift-apidocs-gen#6]
Include support levels based on API group and version, with an override available per API. The support level is just a string value for display with the API details. Possible schema:

```yaml
apiSupportLevels:
- apiGroup: openshift.io
  supportLevels:
  - apiVersion: v\d+
    level: 1
  - apiVersion: v\d+beta
    level: 2
  - apiVersion: v\d+alpha
    level: 4
```

For each `apiGroup`, iterate through supported levels until a version match is found.

These should be complete regular expressions, with the expectation that each is bounded by `^` and `$`.
