### ISSUE TITLE
Feat: Ignore a resource when building

### ISSUE THREAD

**Issue by jboxman** [jboxman/openshift-apidocs-gen#8]
So this is specifically internal only, but oddly shows up in the API anyway:

```yaml
  - kind: RangeAllocation
    group: security.internal.openshift.io
    version: v1
    plural: rangeallocations
    namespaced: false
```

This ought to be ignored even though it appears in `oc api-resources`.
