### ISSUE TITLE
Feat: Expanded config file

### ISSUE THREAD

**Issue by jboxman** [jboxman/openshift-apidocs-gen#9]
Right now, the configuration file is just the _map_ file. But additional configuration options cannot be integrated into this file. So a `v2` file might resemble the following:

```yaml
version: 2
outputDir: build
apisToHide: []
apiSupportLevels: {}
packageMap: {} # replace regex
apiMap:
  - name: Authorization APIs
    resources:
    - kind: LocalResourceAccessReview
      group: authorization.openshift.io
      version: v1
      plural: localresourceaccessreviews
      namespaced: true
```

This file should live in `process.cwd()`. If not, it can be specified on the CLI.
